# Generated by Django 3.2 on 2023-12-07 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0013_project_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='first_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='emp_app.employee'),
        ),
    ]
