# Generated by Django 3.2 on 2023-12-07 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0014_alter_project_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='first_name',
        ),
    ]
