# Generated by Django 3.2 on 2023-12-14 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0016_project_dept'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='dept_name',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='name',
            new_name='role_name',
        ),
    ]
